sudo: required
sevices:
  - docker

before_install:
  - docker build -t lukabulatovic/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lukabulatovic/docker-react npm test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-313358638246"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY