sudo: required
sevices:
  - docker

before_install:
  - docker build -t lukabulatovic/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lukabulatovic/docker-react npm test -- --coverage
  